version: "3"

services:
  levidnode0:
    container_name: levidnode0
    image: "levid/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-levid.log}
    volumes:
      - ./localnet-setup/node0/levid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  levidnode1:
    container_name: levidnode1
    image: "levid/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-levid.log}
    volumes:
      - ./localnet-setup/node1/levid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  levidnode2:
    container_name: levidnode2
    image: "levid/node"
    environment:
      - ID=2
      - LOG=${LOG:-levid.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/levid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  levidnode3:
    container_name: levidnode3
    image: "levid/node"
    environment:
      - ID=3
      - LOG=${LOG:-levid.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/levid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
